licenze:
    token: RUdP84dDyMkpFsPEiy
    type: ""
    expiration: "2025-06-04"
    accound-id: "99270614"
    last-check: "2025-06-01"
    secret: ujtdpernfp
    status: active
server:
    name: Duplex
    type: Школа
    url: https://example.org/
    address: Толчачева, 18
    phone: "+79523235502"
    email: antalkon789@gmail.com
    contact-person: Иванов Иван Ивонович
    id: abbbcdefghijklmnopqrstuvwxyz
    frist: true
    timezone: Europe/Moscow
    language: en
zentas-api:
    token: ""
    id: ""
