licenze:
    token: jmY10sUqS5YW5Hs9fG
    type: paid
    expiration: "2025-09-24"
    accound-id: "16626424"
    last-check: "2025-09-21"
    secret: wxuylajbbu
    status: active
server:
    name: Duplex
    type: Школа
    url: https://example.org/
    address: Толчачева, 18
    phone: "+79523235502"
    email: antalkon789@gmail.com
    contact-person: Иванов Иван Ивонович
    id: abbbcdefghijklmnopqrstuvwxyz
    frist: true
    timezone: Europe/Moscow
    language: en
zentas-api:
    token: ""
    id: ""
