licenze:
    token: NJRjwaiCkswrKUMW80
    type: free
    expiration: "2025-05-05"
    accound-id: "77463970"
    last-check: "2025-05-02"
    secret: ctvzfwdiff
    status: active
server:
    name: Duplex
    type: Школа
    url: https://example.org/
    address: Толчачева, 18
    phone: "+79523235502"
    email: antalkon789@gmail.com
    contact-person: Иванов Иван Ивонович
    id: abbbcdefghijklmnopqrstuvwxyz
    frist: true
    timezone: Europe/Moscow
    language: en
zentas-api:
    token: NZA8hNgIQ02Ro8sp3P
    id: OZ66jUWl1bxv
