licenze:
    token: n8rxzcS4HtMbOLRoqr
    type: free
    expiration: "2025-05-03"
    accound-id: "73197375"
    last-check: "2025-05-01"
    secret: embbsjxszk
    status: active
server:
    name: Duplex
    type: Школа
    url: https://example.org/
    address: Толчачева, 18
    phone: "+79523235502"
    email: antalkon789@gmail.com
    contact-person: Иванов Иван Ивонович
    id: abbbcdefghijklmnopqrstuvwxyz
    frist: true
    timezone: Europe/Moscow
    language: en
zentas-api:
    token: ZwtJxxW33hp8RD7GtI
    id: 7EhjWaZRbPfB
