licenze:
    token: n8rxzcS4HtMbOLRoqr
    type: free
    expiration: "2025-05-03"
    accound-id: "73197375"
    last-check: "2025-04-30"
    secret: hgzauxdtuc
    status: active
server:
    name: Дуплекс
    type: school
    url: https://example.com
    address: г. Москва, ул. Ленина, д. 1
    phone: +7 (495) 123-45-67
    email: antalkon789@gmail.com
    contact-person: Иванов Иван Иванович
    id: abbbcdefghijklmnopqrstuvwxyz
    frist: true
zentas-api:
    token: abcdefghijklmnopqrstuvwxyz
    id: "123456789"
