licenze:
    token: abcdefghijklmnopqrstuvwxyz
    type: free
    expiration: "2025-05-03"
    accound-id: ""
    last-check: "2023-10-01"
    secret: ncidyorevl
    status: active
server:
    name: Дуплекс
    type: school
    url: https://example.com
    address: г. Москва, ул. Ленина, д. 1
    phone: +7 (495) 123-45-67
    email: antalkon789@gmail.com
    contact-person: Иванов Иван Иванович
    id: abbbcdefghijklmnopqrstuvwxyz
zentas-api:
    token: abcdefghijklmnopqrstuvwxyz
    id: "123456789"
