name: Code Metrics

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Run cloc
        run: cloc --by-file --include-lang=Go,YAML,JavaScript,JSON,Markdown .